#!/bin/python3

from selenium import webdriver
from selenium.webdriver.common.by import By
import time, random, string


def write_text(text, time_mod=0.2):
    for c in text:
        sec = random.gauss(time_mod, time_mod / 2)
        webdriver.ActionChains(firefox)\
                .send_keys(c)\
                .perform()
        time.sleep(abs(sec))


options = webdriver.FirefoxOptions()
options.add_argument("-headless")
options.add_argument("window-size=1400,600")

firefox = webdriver.Firefox(options=options)

firefox.set_window_size(1920, 1080)


try:
    firefox.get("https://translate.google.com/")
except:
    pass

firefox.implicitly_wait(4)
time.sleep(5)


lorem_sentences = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lacus sed turpis tincidunt id aliquet risus. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Vel fringilla est ullamcorper eget nulla facilisi. Nisl suscipit adipiscing bibendum est ultricies. Risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Euismod lacinia at quis risus sed vulputate. Convallis convallis tellus id interdum velit laoreet id. Morbi enim nunc faucibus a. Placerat duis ultricies lacus sed turpis tincidunt. Porttitor leo a diam sollicitudin tempor id eu nisl. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Eu augue ut lectus arcu bibendum at. Id velit ut tortor pretium viverra suspendisse. Quam lacus suspendisse faucibus interdum. Vitae auctor eu augue ut lectus arcu bibendum. Eu feugiat pretium nibh ipsum consequat.
Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Imperdiet proin fermentum leo vel orci porta non. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Sit amet porttitor eget dolor morbi non. Amet purus gravida quis blandit. Suspendisse in est ante in nibh mauris cursus mattis molestie. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Sed vulputate odio ut enim blandit volutpat maecenas. Ultricies integer quis auctor elit sed vulputate mi sit. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Lectus magna fringilla urna porttitor rhoncus dolor purus. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Suspendisse in est ante in nibh. Ultricies tristique nulla aliquet enim. Urna cursus eget nunc scelerisque viverra mauris in aliquam sem. Arcu cursus vitae congue mauris rhoncus. Vitae congue mauris rhoncus aenean vel elit. Nisi vitae suscipit tellus mauris a diam maecenas sed. Pulvinar elementum integer enim neque volutpat ac.
Duis at tellus at urna condimentum mattis pellentesque id nibh. Tincidunt eget nullam non nisi est sit amet facilisis magna. Dolor purus non enim praesent elementum. Volutpat blandit aliquam etiam erat. Justo laoreet sit amet cursus sit amet dictum. Turpis massa sed elementum tempus egestas sed sed risus pretium. Vel quam elementum pulvinar etiam non quam lacus. Ac turpis egestas sed tempus. Commodo nulla facilisi nullam vehicula ipsum a. Lorem donec massa sapien faucibus et molestie ac feugiat. Dui ut ornare lectus sit amet. Habitasse platea dictumst quisque sagittis purus sit amet.
Pellentesque nec nam aliquam sem et tortor consequat id. Ornare arcu odio ut sem. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Magna eget est lorem ipsum. Malesuada pellentesque elit eget gravida cum sociis. Lobortis mattis aliquam faucibus purus in massa. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Viverra accumsan in nisl nisi. Elementum nibh tellus molestie nunc non blandit massa enim nec. Libero volutpat sed cras ornare arcu dui. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Ut etiam sit amet nisl purus in mollis.
Facilisis sed odio morbi quis commodo odio aenean sed. Pharetra pharetra massa massa ultricies mi quis. Nisl tincidunt eget nullam non nisi est sit. Velit aliquet sagittis id consectetur purus. Elementum eu facilisis sed odio morbi quis. Praesent elementum facilisis leo vel fringilla est. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Tincidunt praesent semper feugiat nibh sed. Risus ultricies tristique nulla aliquet enim tortor. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Id ornare arcu odio ut sem nulla pharetra diam sit. Vel eros donec ac odio tempor orci dapibus ultrices. Eget gravida cum sociis natoque. Ultrices tincidunt arcu non sodales neque. Mollis nunc sed id semper.
Dui accumsan sit amet nulla facilisi morbi tempus. In fermentum posuere urna nec tincidunt praesent. Malesuada fames ac turpis egestas. Dolor magna eget est lorem ipsum. Erat pellentesque adipiscing commodo elit at imperdiet. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Urna nunc id cursus metus aliquam eleifend. Egestas diam in arcu cursus euismod quis viverra. Libero enim sed faucibus turpis in eu mi bibendum neque. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Dictum fusce ut placerat orci nulla. Nisi vitae suscipit tellus mauris a diam maecenas sed. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Et odio pellentesque diam volutpat commodo sed egestas egestas. Interdum posuere lorem ipsum dolor sit amet. Nunc mattis enim ut tellus. Velit egestas dui id ornare.
Gravida arcu ac tortor dignissim convallis aenean et tortor at. Non odio euismod lacinia at quis risus. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Neque volutpat ac tincidunt vitae semper quis. Malesuada fames ac turpis egestas sed tempus urna et. Ultrices sagittis orci a scelerisque purus semper eget duis. Rutrum quisque non tellus orci ac. Risus pretium quam vulputate dignissim suspendisse in est ante. Sed adipiscing diam donec adipiscing tristique. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Ornare lectus sit amet est placerat in egestas. Leo integer malesuada nunc vel risus commodo. Cum sociis natoque penatibus et magnis dis. Commodo elit at imperdiet dui accumsan sit amet. Elit ut aliquam purus sit amet luctus venenatis lectus.
Malesuada proin libero nunc consequat interdum varius. Nibh sed pulvinar proin gravida. Purus sit amet luctus venenatis lectus. In aliquam sem fringilla ut morbi. Sem fringilla ut morbi tincidunt. Amet porttitor eget dolor morbi non arcu risus quis. Scelerisque in dictum non consectetur a erat nam at. Mauris vitae ultricies leo integer malesuada nunc vel. Id velit ut tortor pretium. Mi quis hendrerit dolor magna. Viverra tellus in hac habitasse platea dictumst vestibulum. Fames ac turpis egestas integer eget aliquet nibh.
Morbi blandit cursus risus at ultrices mi. Sollicitudin aliquam ultrices sagittis orci. Cursus risus at ultrices mi. Ultrices gravida dictum fusce ut placerat orci nulla. Ipsum nunc aliquet bibendum enim facilisis. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Cras semper auctor neque vitae tempus. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Dolor sit amet consectetur adipiscing elit. Lacus sed turpis tincidunt id aliquet risus feugiat in. Mi eget mauris pharetra et ultrices neque. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Arcu odio ut sem nulla pharetra diam sit. Scelerisque fermentum dui faucibus in ornare quam. Suscipit adipiscing bibendum est ultricies integer. In egestas erat imperdiet sed euismod nisi porta lorem. Vel risus commodo viverra maecenas accumsan. Nulla facilisi etiam dignissim diam quis enim lobortis. Posuere morbi leo urna molestie at elementum eu.
Nec feugiat nisl pretium fusce id. Tortor condimentum lacinia quis vel eros. Ac ut consequat semper viverra nam libero justo laoreet. Sit amet luctus venenatis lectus magna fringilla. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Montes nascetur ridiculus mus mauris vitae. Nisl suscipit adipiscing bibendum est ultricies integer. Libero enim sed faucibus turpis in eu mi bibendum. Egestas integer eget aliquet nibh praesent tristique. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Lobortis feugiat vivamus at augue. Suscipit tellus mauris a diam maecenas sed enim ut sem. Quis enim lobortis scelerisque fermentum. Scelerisque eu ultrices vitae auctor.
Lectus quam id leo in vitae turpis massa. Urna duis convallis convallis tellus id interdum velit. Egestas dui id ornare arcu odio ut. Tortor at risus viverra adipiscing at in tellus integer. Viverra ipsum nunc aliquet bibendum. Etiam sit amet nisl purus in. Tortor at auctor urna nunc id cursus metus. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Varius sit amet mattis vulputate enim. Eu ultrices vitae auctor eu augue. Viverra justo nec ultrices dui sapien eget mi proin sed. Mauris sit amet massa vitae tortor condimentum lacinia quis. Integer quis auctor elit sed vulputate mi. Tincidunt tortor aliquam nulla facilisi cras fermentum odio.
Elit ut aliquam purus sit. Arcu odio ut sem nulla pharetra diam sit. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Nulla aliquet enim tortor at auctor. Imperdiet sed euismod nisi porta lorem. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Sed felis eget velit aliquet sagittis id consectetur purus ut. Nisl tincidunt eget nullam non. Morbi tincidunt ornare massa eget. Facilisis gravida neque convallis a cras semper auctor neque.
Non pulvinar neque laoreet suspendisse interdum consectetur libero. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Urna duis convallis convallis tellus id interdum velit. Egestas sed sed risus pretium quam vulputate dignissim. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Suscipit tellus mauris a diam maecenas sed. Id velit ut tortor pretium viverra. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Lectus vestibulum mattis ullamcorper velit. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Leo a diam sollicitudin tempor id eu.
Non odio euismod lacinia at quis risus sed vulputate. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Volutpat odio facilisis mauris sit. At volutpat diam ut venenatis tellus in metus. Pharetra et ultrices neque ornare aenean euismod elementum. Urna nunc id cursus metus aliquam eleifend mi. Enim nunc faucibus a pellentesque sit amet porttitor. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Erat imperdiet sed euismod nisi. Ipsum suspendisse ultrices gravida dictum fusce.
Neque viverra justo nec ultrices. Turpis egestas integer eget aliquet nibh praesent tristique magna. Eget mauris pharetra et ultrices neque ornare. Varius duis at consectetur lorem donec massa sapien faucibus et. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Mauris nunc congue nisi vitae suscipit tellus mauris a diam. Vel eros donec ac odio tempor orci. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Nunc faucibus a pellentesque sit amet. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Magna ac placerat vestibulum lectus mauris ultrices. Neque ornare aenean euismod elementum nisi quis eleifend quam. Sed risus ultricies tristique nulla aliquet enim tortor. Suspendisse ultrices gravida dictum fusce ut. At tellus at urna condimentum. Gravida arcu ac tortor dignissim convallis. Proin sed libero enim sed faucibus turpis. Sed egestas egestas fringilla phasellus faucibus scelerisque. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Nunc aliquet bibendum enim facilisis gravida neque convallis.
A diam maecenas sed enim ut sem viverra aliquet. Phasellus egestas tellus rutrum tellus. Odio facilisis mauris sit amet massa vitae. Eu volutpat odio facilisis mauris sit amet massa. Accumsan sit amet nulla facilisi morbi tempus. Ultrices dui sapien eget mi proin. Facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Dignissim enim sit amet venenatis. Ac felis donec et odio pellentesque diam. Commodo elit at imperdiet dui accumsan sit amet nulla. Aenean et tortor at risus viverra adipiscing at in tellus. Maecenas sed enim ut sem. Auctor elit sed vulputate mi sit amet. Facilisis magna etiam tempor orci. Ornare arcu odio ut sem nulla pharetra diam sit. Amet purus gravida quis blandit turpis cursus in hac. Leo urna molestie at elementum eu.
Turpis cursus in hac habitasse platea dictumst quisque sagittis. Ornare aenean euismod elementum nisi. A erat nam at lectus. Sagittis orci a scelerisque purus semper eget. Urna nunc id cursus metus aliquam eleifend mi. Ac placerat vestibulum lectus mauris ultrices eros. Pellentesque elit ullamcorper dignissim cras tincidunt. Platea dictumst quisque sagittis purus. Fringilla ut morbi tincidunt augue. Turpis in eu mi bibendum neque. Pellentesque habitant morbi tristique senectus. Gravida rutrum quisque non tellus orci ac. Eget aliquet nibh praesent tristique magna sit amet purus. Non curabitur gravida arcu ac tortor dignissim. Mollis aliquam ut porttitor leo a diam. Integer enim neque volutpat ac tincidunt vitae semper. Mattis pellentesque id nibh tortor id aliquet lectus. Non sodales neque sodales ut. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper.
Laoreet sit amet cursus sit amet dictum sit amet justo. Condimentum vitae sapien pellentesque habitant. Sit amet mauris commodo quis imperdiet massa. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Risus feugiat in ante metus dictum at tempor commodo. Et leo duis ut diam quam nulla porttitor. Ut sem viverra aliquet eget sit amet tellus cras. Commodo nulla facilisi nullam vehicula. Vulputate eu scelerisque felis imperdiet proin. Pretium fusce id velit ut tortor pretium viverra. Arcu risus quis varius quam quisque id diam vel. Massa ultricies mi quis hendrerit dolor magna eget est lorem. Orci a scelerisque purus semper. Et pharetra pharetra massa massa ultricies. Sed adipiscing diam donec adipiscing. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Facilisi nullam vehicula ipsum a arcu cursus. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Curabitur gravida arcu ac tortor dignissim convallis.
In massa tempor nec feugiat nisl pretium. Nisl condimentum id venenatis a condimentum vitae sapien. At augue eget arcu dictum varius duis at. Enim ut tellus elementum sagittis vitae. Vulputate ut pharetra sit amet. Amet risus nullam eget felis eget nunc lobortis mattis aliquam. Vitae turpis massa sed elementum tempus. Eget arcu dictum varius duis. Et tortor consequat id porta nibh venenatis cras. A iaculis at erat pellentesque. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Lorem ipsum dolor sit amet. Semper risus in hendrerit gravida rutrum quisque non tellus. Sed risus pretium quam vulputate dignissim suspendisse. Tellus molestie nunc non blandit massa. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Id diam vel quam elementum pulvinar etiam non. Risus in hendrerit gravida rutrum quisque non.
Eros donec ac odio tempor orci. Libero volutpat sed cras ornare arcu dui vivamus arcu. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Eu augue ut lectus arcu bibendum. Fusce ut placerat orci nulla pellentesque dignissim. Consectetur purus ut faucibus pulvinar elementum integer enim. Diam ut venenatis tellus in metus vulputate eu. Massa tincidunt dui ut ornare lectus sit. Aliquam etiam erat velit scelerisque in dictum. Semper risus in hendrerit gravida. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Eu consequat ac felis donec et odio. Lacus viverra vitae congue eu consequat ac felis donec et. Nunc id cursus metus aliquam. Vitae tortor condimentum lacinia quis vel eros donec ac. Ut enim blandit volutpat maecenas volutpat. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Pulvinar mattis nunc sed blandit libero volutpat.
""".split(".")

# Pick random number of sentences to translate
num_lines = random.randint(0, len(lorem_sentences))
# Pick random starting point
starting = random.randint(0, len(lorem_sentences) - num_lines)

text_to_translate = '.'.join(lorem_sentences[starting:num_lines])

write_text(text_to_translate)


while True:
    continue

